### ISSUE TITLE
Yeelighter error for ceiling14

### ISSUE THREAD

**Issue by tangone2** [cellcortex/homebridge-yeelighter#122]
Hi,
I have yeelight ceiling14 and I installed the Yeelighter plugin to connect to it in homebridge but encountered error below:
[Yeelighter] ingoring device with corrupt DeviceInfo {
  location: 'yeelight://undefined',
  id: undefined,
  model: undefined,
  support: undefined,
  power: false,
  bright: 0,
  color_mode: -1,
  ct: 0,
  rgb: 'string',
  hue: 0,
  sat: 0,
  host: 'string',
  port: 0,
  debug: false,
  trackedAttributes: [],
  fw_ver: '0,0.0',
  name: 'string'
}
Appreciate any suggestion how to solve this issue.
Thanks.

**Comment by cellcortex** [comment]
Looks like you have manually configured a device in the config. Removing that should solve this.

**Comment by tangone2** [comment]
below is the default settings from the config, is it not correct? how should I change it? 

{
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": false,
            "split": true,
            "manual": [
                {
                    "ignorePower": false
                }
            ],
            "platform": "Yeelighter"
        },

**Comment by tangone2** [comment]
and the error:

![Uploading 637E00E5-7B49-4FD2-9381-5DB259E0B4CA.jpeg…]()

**Comment by tangone2** [comment]
and the error:

![E0AF0E94-23DE-4A6E-A61A-4397A5132817](https://user-images.githubusercontent.com/55867503/181780138-e9b1405a-76cd-4d89-97d1-7650d37acd38.jpeg)

**Comment by Idomo** [comment]
It looking at each object in the `"manual"` array as a device, since you've created a "device" with only `"ignorePower"` parameter, it says that the data of this device is corrupted (missing `"id"` and `"address"` that are required).

Just remove `{ "ignorePower": false }` from the `"manual"` array.

**Update:**
It seems like disabling and re-enabling of the `LAN Control` in the Yeelight app has been the solution for the discovery issues.
*Remove any manual configurations from the JSON file before then.
