### ISSUE TITLE
Cache Notification Loop

### ISSUE THREAD

**Issue by fabaklava** [cellcortex/homebridge-yeelighter#133]
Hi everyone, I ran this plugin with Homebridge successfully for a while, however know I keep getting config change and cache notifications every 2-3 minutes or so which seems to drag down my Homebridge instance. and install this plugin, and it's work out of the box for quite sometimes.

**I connected these devices:

* 4 Yeelight LED Bulb 1S
* 2 Yeelight Meteorite Ceiling Lamps

I've tried to re-install the plugin, manually add lights, create a child bridge, etc.

Configuration Notifications: 

```
[2/28/2023, 10:50:03 AM] [Yeelighter] [0x0000000013fXXXXX] setting name to "color4". []
[2/28/2023, 10:50:03 AM] [Yeelighter] [0x0000000013fXXXXX] Ingoring updateName [ 'color4' ]
```

Cache Notifications:

`[2/28/2023, 10:34:45 AM] [Yeelighter] New (cached) color4 [0x0000000013f2XXXX] found at yeelight://192.168.178.XX:XXXXX”`

**Comment by rdmn7** [comment]
I have the same problem, don’t know why this happens. Have you found a solution?

**Comment by cellcortex** [comment]
These would happen if the lights are broadcasting their "hello" to the network. The should normally do it only when they are switched on (or reacting to a broadcast from the plugin asking to find any lamps on the network). 
You could probably reduce the logging but my guess is that the problem lies in the network (maybe some power management or so).
