### ISSUE TITLE
Alexa Skill - Dublicate Error

### ISSUE THREAD

**Issue by alert82** [cellcortex/homebridge-yeelighter#31]
Hello im using also the alexa Skill, and i get a Dublicate Error - i think thats because the light with the backlight ist 2 times in Homebridge and messes up Alexa 

[6/5/2020, 14:05:56] [Alexa] WARNING: Duplicate device name GuangCan Ceiling Light
[6/5/2020, 14:05:56] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => GuangCan Ceiling Light
[6/5/2020, 14:05:56] [Alexa] alexaDiscovery - returned 17 devices
[6/5/2020, 14:20:56] [Alexa] WARNING: Duplicate device name GuangCan Ceiling Light
[6/5/2020, 14:20:56] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => GuangCan Ceiling Light

**Comment by NorthernMan54** [comment]
@cellcortex Is it feasible to have the second light service name ( background ) add some text to the name so that the homebridge-alexa plugin can differentiate between the two?  At the present time as the names are duplicate, the second one is not passed too Alexa.

https://github.com/NorthernMan54/homebridge-alexa/issues/336

**Comment by cellcortex** [comment]
I should be able to add an option to have added to the config.

**Comment by NorthernMan54** [comment]
Tks, much appreciated

**Comment by eliac7** [comment]
Hey @cellcortex , did you managed to fix that? Or can you point us on how to fix it manually?
Thanks in advance.

**Comment by cellcortex** [comment]
Didn't get to it. If you want to take a shot, I'm happy to accept a PR. You would need to create 2 accessories for those lights instead of one.

**Comment by NexGen-3D-Printing** [comment]
Hi, have similar issues with duplicates and the Alexa plugin.

Also, if you have 2 identical lights, in my case they are both detected as color4, they will both show in Homekit but when using the Alexa Hombridge Skill, only one light will detect, and it fails to operate due to the duplication of the detected name.

Below is what comes up in Homebridge and its passing the "Model" through to the Alexa Skill plugin, not the "Name", as I change the name, but it still detects as color4, I have also tried to change the ID but that only changes the "Serial Number"

Lightbulb	
On	false
Brightness	5%
Color Temperature	370
Hue	282
Saturation	100%
Manufacturer	Yeelighter
Model	color4
Name	color4
Serial Number	0x000010101018dc9f
Firmware Revision	27
Homebridge Instance IP	127.0.0.1
Homebridge Instance Port	51100
Homebridge Instance Username	0E:69:8E:D8:4E:21
aid	12
iid	8

**Comment by NorthernMan54** [comment]
@cellcortex Recently identified is that the [Configured Name](https://developers.homebridge.io/#/characteristic/ConfiguredName) characteristic will receive set events when an accessory name is changed in the Home app.  And if you could add the characteristic, I can read the values in the homebridge-alexa plugin.

Change is something like this


```
this.services[uniq_id].service.getCharacteristic(this.Characteristic.ConfiguredName)
              .on('set', setConfiguredName.bind(this.services[uniq_id]));
```

```
function setConfiguredName(this: tasmotaSwitchService | tasmotaLightService | tasmotaFanService | tasmotaSensorService | tasmotaBinarySensorService, value, callback: CharacteristicSetCallback) {
  // debug('this', this.service.displayName);
  // this.platform.log.debug('setConfiguredName', value, this.service.displayName);
  this.service.displayName = value;
  this.service.setCharacteristic(this.platform.Characteristic.Name, this.service.displayName);
  this.platform.api.updatePlatformAccessories([this.accessory]);
  callback();
}
```

**Comment by plantoschka** [comment]
Would be really happy if this gets fixed because I do some dynamics brightness adjustments trough NodeRed and this currently does not work for a second device called „Ceiling Light“.
https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/issues/30#issuecomment-731807060

**Comment by NorthernMan54** [comment]
@cellcortex Tks
